name: eatcost_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.4.7

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^6.0.0

flutter_native_splash:
  color: "#F7F7F8"
  image: assets/splash/splash-logo.png
  android_12:
    image: assets/splash/splash-logo.png
    color: "#F7F7F8"

flutter:
  assets:
    - assets/images/

  uses-material-design: true

  fonts:
    - family: FFGoodPro
      fonts:
        - asset: assets/fonts/FFGoodPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/FFGoodPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/FFGoodPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/FFGoodPro-Light.ttf
          weight: 300
        - asset: assets/fonts/FFGoodPro-Black.ttf
          weight: 900
